name: Test Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        retry: [1, 2, 3]  # Кількість повторів
      max-parallel: 2      # Ліміт на одночасне виконання

    name: Deploy Attempt ${{ matrix.retry }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log Deploy Attempt
        run: |
          echo "Attempting deployment: ${{ matrix.retry }}"
          # Script for deploy, for example:
          # az webapp up --name your_app_name --resource-group your_resource_group
          
          # Simulation of failure
          if [[ ${{ matrix.retry }} -lt 3 ]]; then
            echo "Simulating failure..."
            exit 1  # Call error for testing retries
          else
            echo "Deployment succeeded on attempt ${{ matrix.retry }}"
          fi
